volumes:
  web_data:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - web_data:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: book_store_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - db
