version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Map port 80 of the container to 8081 on the host
    volumes:
      - ./Book_Store:/var/www/html:cached  # Add ':cached' for better performance on host-to-container mounts
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: book_store_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_store_db
    volumes:
      - db_data:/var/lib/mysql  # Persist database data across container restarts

volumes:
  db_data:  # Define named volume for the database
