version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - web_data:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: book_store_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_store_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  web_data:
    driver: local
  db_data:
    driver: local
